version: "3.9"

services:

  postgres:

    image: postgres:16

    container_name: trustosai-postgres

    restart: always

    environment:

      POSTGRES_USER: trustos

      POSTGRES_PASSWORD: trustos_password

      POSTGRES_DB: trustosai


    ports:

      - "5432:5432"


    volumes:

      - postgres_data:/var/lib/postgresql/data



volumes:

  postgres_data: